### PR TITLE
Fixed for working with Ubuntu 22.04 in docker containers; cd Containe…

### PR DESCRIPTION
**Pull request by tacitness**
Fixed for working with Ubuntu 22.04 in docker containers; 

  cd Containers/;
  cp -r docker-ubuntu-2{1,2}.04/
  perl -pi -e 's/21.04/22.04/g' docker-ubunut-22.04/Dockerfile; 

Voila, works to run docker container on Ubuntu 22.04;

### CODE REVIEW

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
cc @brandon-rhodes

**Comment by brandon-rhodes** [comment]
Thanks for the bump! You've caught me on a good day: with other obligations evening out, I'm sitting down this week to look over my open source projects.

I could quibble with the line `NAME=xephem-ubuntu-21.04` in this PR, but given that I've kept you waiting since October, how about I go ahead and fix it myself!

**Comment by pidloop** [comment]
I'm curious what data these containers include. I assume the text catalogs,
but what about the guide stars?

**Pull request merged**
