### PR TITLE
Uranus (and his moons) IMCCE/BDL period 2020-2040 coefficients data-file added.

### PR DESCRIPTION
**Pull request by obspsr**
Uranus (and his moons) IMCCE/BDL period 2020-2040 coefficients data-file added. Uranus 2020-2040 relative C code upgraded.

### CODE REVIEW

**Comment by obspsr** [comment]
Saturn (and his moons) IMCCE/BDL period 2020-2040 coefficients. End of data upgrade !
Do not forget to copy all *.2040 files to your XEphem local  xephem/auxil/ directory.

**Comment by obspsr** [comment]
Reopened these 9 commits pull request. (it is not evident what is selected and what is not !!
Thanks for coop.
Serge.

**Comment by brandon-rhodes** [comment]
@obspsr — How can I test locally whether I've merged this correctly? I tried re-compiling, then running XEphem, then setting the date to 12/31/2039 and stepping forward. I expected there to be a jump in moon positions for Jupiter when I crossed the date of 2040, but I didn't see the positions jump, they looked rather smooth as the last day of 2039 changed to 2040.

**Comment by obspsr** [comment]
Hi Brandon, it is not evident at first ! You just have to copy *.9910, *.1020, *.2040 in your active auxil directory (...mine is /usr/local/xephem/auxil/ ). All files are necessary to cover the span 1999-2041.
Good evening,
Serge

**Comment by brandon-rhodes** [comment]
> You just have to copy … to your active auxil directory …

Happily, that's not necessary when I run XEphem directly from the directory where `make` puts it — as long as my current directory is `GUI/xephem/` in the source tree, XEphem seems to find the file just fine.

> I have checked all Saturn, Jupiter, Mars and Uranus moons position …

Could you outline in detail how you ran your checks? When I check out your branch, the files do not work with XEphem. For example, the `jupiter.2040` file produces this when I try to ask for a position on 2466519.5:

    BDL unexpected EOF

I have just spent a half-hour with the BDL code in XEphem, and I think I have found one problem (though maybe there are more?): XEphem assumes that every data line of the `jupiter.2040` is exactly the same length, so that it can measure the length of the first line, and then multiply to figure out where the “n”th record is in the file.

But the `jupiter.2040` in your branch does not have lines of equal length, so XEphem cannot find records in the file.

I think you should be able to verify that the old `jupiter.*` files have data lines of the same length, and that they therefore work with XEphem.

Could you double-check whether `jupiter.2040` is formatted correctly, and see if it needs to be updated to produce equal-length lines? Also, the other new files will need to meet the same requirement.

**Comment by brandon-rhodes** [comment]
With some other projects having concluded, I finally had time this morning to extract the data-file commits from your branch and get them committed to the main repository. Thanks again for providing these!

**Pull request closed without merging**
