### PR TITLE
4.1.0: src

### PR DESCRIPTION
**Pull request by zvezdochiot**
Move source code to `src`. No change code.

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
I find the files easier to get to without the extra `src/` level of directory structure; and, many XEphem users are familiar with the current directory layout through years of work with the project and it will benefit them for it to remain the same; and, I think of a repository on GitHub as already implying “source” without needing a directory of that name to remind me what’s in the repository—so I am inclined to leave the files where they currently are. But, I am interested in hearing the motivation behind the extra directory level if you could explain your approach.

**Comment by zvezdochiot** [comment]
Hi @brandon-rhodes .

The motivation is simple. I bring all the repos to a single form.

**Comment by pidloop** [comment]
But this ignores the legacy context. [Consistency is boring](https://www.goodreads.com/quotes/353571-a-foolish-consistency-is-the-hobgoblin-of-little-minds-adored)

**Comment by brandon-rhodes** [comment]
As this will cause disruption for the community who has long lived with this source code, let's shelve this approach for now. We can re-open this idea at any point in the future if the current directory structure runs into problems that at this point are not yet foreseen, so I am going ahead and closing it for now.

**Pull request closed without merging**
