### PR TITLE
Delta T table 2012-2018 added. Pluto orbital parameters of 2020 Almanach. MPC obs codes added.

### PR DESCRIPTION
**Pull request by rmathar**

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
1. Thanks for these contributions!
2. I have gone ahead and committed your changes to `libastro/plans.c` and `libastro/deltat.c`, and they are now part of the official branch.
3. I added them as two different commits to make the history easier to read, and also so that if either of them ever has to be reverted, it will not harm the other file change.
4. If you make a future contribution, it’s simplest to put your comments about a Pull Request right on the Pull Request page itself. It took me a few minutes to figure out that your description of this PR was over on #2 instead of being here, :slightly_smiling_face: which splits our discussion of this PR across two different places.
5. I have not yet merged your additions to `xephem_sites` because (a) it duplicates many observatories like Greenwich in England and I think we should only have one copy of each observatory, (b) the leading numbers and letters seem to break the convention of how the names are formatted in the rest of the file and I would like more discussion about that, and (c) as you say, the time zones are missing. It feels like more discussion is needed before this big change goes out and affects all XEphem users?

**Comment by rmathar** [comment]
A list of the MPC sites (approximately 2300 as of today) including time zones is now in

https://owncloud.gwdg.de/index.php/s/aJIjsTKWY86KTZI

A list of the "original" roughly 500 sites that have been created in 1992 and are in the xephem 4.1.0 distribution is in

https://owncloud.gwdg.de/index.php/s/RzU9zDstBTZNjfC

The time zones that are listed with explicit switch-over specifications in the "original" xephem_sites file have been replaced with the modern time zone names, such that the operating system will look up which time zones are in use during which periods. Note that XEphem uses tzset(3) to read the time zones in the 5th field, so that format will work.

These files have been created by piping the longitude/latitude coordinates through the Java Timeshape class of https://github.com/RomanIakovlev/timeshape

**Comment by brandon-rhodes** [comment]
I’ve looked over your `xephem_sites3` and have tried it out\! After some experimentation, I have been inspired to write up a list of design constraints on the “sites” file that I think are imposed on us by XEphem’s traditions and by the practices of XEphem’s existing user base. Here’s a first draft of four design principles, about which I welcome discussion:

**1. Once added to the file, an entry should never disappear and never change its spelling.** Users are invited to save their current location setting for use the next time they run XEphem. I just tested, and after changing the file, the name of my saved setting still displays, but becomes Latitude 0:00:00 and Longitude 0:00:00 if the new “sites” file does not list my location with exactly the same spelling as before. So I think entries should be stable once added, so that new versions of XEphem don’t break the settings of existing users. (This isn’t an obstacle to new entries, of course: it just means that new entries must be added to the existing file, rather than replacing old entries.)

**2. Site names should start with letters, not numbers.** The current sites file produces a site dialog with names in alphabetical order. This makes them very easy to scroll and browse. If leading numbers are added, then scrolling becomes far less useful — I don’t know where to scroll to look for a particular entry:

image

(By the way — do you know why every location is listed twice? Does that happen to you, or only on my computer?)

**3. Entries should always include their country.** Otherwise I don’t know which “Montpelier” is being specified.

**4. Time zones must, alas, remain in traditional Unix format.** Just yesterday I was responding to a user who runs XEphem under CDE on an old HP-UX workstation. I double-checked some HP-UX documentation for *tzset(3)* and also [a discussion on an online forum](https://community.hpe.com/t5/System-Administration/allowable-settings-for-etc-default-tz/td-p/5189893), and both confirm that HP-UX lacks support for the newfangled `US/Eastern` style time zones. To continue to support our traditional Unix users, we will need to avoid novel conventions. (Or should the file format be expanded to include both, since I suppose that `US/Eastern` — if the underlying OS supports it — is including information that the POSIX.1 format does not, namely, identifying which specific legal daylight savings time regime to apply?)

So I think those are our constraints if we want to keep existing XEphem users happy.

Do you know where in the source tree we might place these guidelines, after whatever discussion and debate is necessary, so that contributors can find them? Would a new `CONTRIBUTING.md` file be an appropriate place, for example?

Even though `xephem_sites3` is more than 4 times larger than the existing file, XEphem seemed to have no problem loading and displaying it, so its code and the dialog box seem easily ready to handle this many new entries. If you have found the MPC list of observatories to be well-maintained and a high quality list of positions, then it does seem reasonable for XEphem to add them, since the existing `xephem_sites` is indeed biased towards observatory sites already. Since you work at Max-Planck, I can ask: is the MPC list considered by astronomers to be a kind of official list of observatories world-wide, and once we’ve added it, the sites file will contain a fairly complete list of observatories? Or is the MPC list focused specifically on observatories doing minor planet work, and a complete list would need further entries added in the future? As I'm not a professional astronomer, this is context that, alas, I lack.

Thanks for the work you're doing here to get the "sites" file expanded — with another couple of tweaks to your draft file, hopefully “Heidelberg” will appear on XEphem's list!

(Or — was it in fact another observatory that you noticed was missing and wanted to fix?)

**Comment by rmathar** [comment]
on 1) Entries should be maintained, which means if time zones change or coordinates or MPC renames things to disambiguate multiple entries, the entry should change. The reason that the observatories higher up in their list have "weak" names is probably historical: When the list was started it was not foreseen that there could be observatories with similar names outside Europe later on.

on 2) To look for a particular entry use the wild cards, like ``*Heid*`` for Heidelberg. There is rarely a reason to scroll...

I don't know why entries appear twice in your screen shot. On my "Site Selection" GUI on a openSUSE 12.3 every entry appears only once if I copy xephem_sites3 into ~/.xephem/xephem_sites .

MPC uses numbers as unique keys (like all rational database do) to disambiguate telescopes in a unique way. Principal keys in rational databases (and CVS files for example) are usually placed in front. The principle supports that, if you have two instruments perhaps on the same telescope at the same time, you could have two tags at the same position of the same observatory in the same time zone, put that OBSCODE in your FITS header etc.

MPC needs unique keys to keep track which planet-hunter has contributed to which orbital elements and discoveries. The 3-letter key is a simple measure to give proper credit to the busy observatories in data lists. It also has the advantage of staying in place even if the observatory should change its name for any kind of political reasons. (Perhaps there are still former Nazi-names somewhere in the list? Who knows....)

I don't know what MPC will use as tags in the far future, because they have approximately 37*100 possible keys (first a letter or digit, second and third a digit), have already used of the order of 2300 of them, and may be running out of keys in a few years. If the first character is a letter, it is a sort of country-code in most cases. In that sense the MPC order is that "old" observatories are first, and other observatories are roughly sorted by country/region.

The only other rational order of listening the sites is by using the latitude (as a first order key) and longitude (second order) akin big star libraries tile the sky into ra/dec rings to split the library into smaller chunks. That way Antarctica Dome C would appear higher up, then Australia, South Africa, a mix of European and US-American.. and finally some Alaska sites and Northern Finland. (Can one avoid law suits by sites listed at the low end of that list?)

on 3) This list is auto-created from the MPC data base. To change it you either need to edit all 2300+ entries (every month or so when the MPC updates the list) manually or to forward a change request to the MPC. I will not put any effort into that.

If you have more than one name like "Montpellier" you ought to search with the wildcard (like ``*Mont*``) in the box, click repeated only "search" and select the one you want.

Why should entries include the country? (Astronomers are far less nationalistic
than others....)

on 4) If time zones must remain in the obsolete traditional Unix format, you need to check the time zones (including the rules for DST) frequently. Note for example that there was a Europe-wide vote last year held by the European Parliament where the majority of the voters voted to remove the switching from/to standard time to daylight-savings time; one cannot tell whether this will actually be implemented.
[I've read in the discussions on time zone changes that once in Turkey Erdoban switched forth and back (within the Ramadan -observing time zone) on a single day during elections... It's impossible to track complicated things like that in the old format.]

Which sites MPC includes is their policy and I cannot comment on that. It seems the official site list of the XEphem was created in the nineties from a satellite dishes list.

The only semi-official use of xephem I've ever seen by "professional" astronomers is a mention in some engineering wiki of the LBTO (Arizona) which says they have a tool to convert their guide star catalogs to the XEphem format. In fact I don't know any other astronomer in person who uses xephem. If it is desired that "professional" astronomers use XEphem, it is important to include the telescopes of the 2-meter-class and larger; you can then drop sites like Greenwich which have no importance in modern astronomy :-)
The number of "telescope-hoppers" in the professional community would be extremely low. Most of them will focus on a handful of instruments on a handful of bigger telescopes.

On a side note: "real" astronomers would set all time zones to UTC. I know at least one Spanish observatory where all computers are set to UTC (not the local time zone) because inside C/C++/Java environments some time-zone-aware libraries coded by non-astronomers are not coded properly. That does no harm inside XEphem because sunset times etc are all tied to the geographic location, which XEphem knows anyway. [And beyond: I had fruitless discussions with "real" astronomers in the past on the topic that "old" non-maintained operating systems have wrong ideas what the correct leap-seconds adjustment is once the operating system is older than the most recent leap-second. People using HP-UX need to keep this in mind.]

**Pull request closed without merging**
